sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-074155400331"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: $SECRET_KEY