sudo: required
services:
- docker
before_install:
- docker build -t docker-react -f Dockerfile.dev .
script:
- docker run docker-react npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-east-1
  app: docker-react2
  env: docker-react2-dev
  bucket_name:
  bucket_path: docker-react2
  on:
    repo: RastriginSergey/docker-react
    branch: main
  skip_cleanup: 'true'
