sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-074155400331"
  on:
    branch: main
  access_key_id:
    secure: "jdYC4NqWkLoFeWSGD9OCiLnDTNutRm7Vhv9m4tut5AI2DsElza6gWa5heiMRSUeMDosi44UpOtENNd77MdhmK5BkHURxjvhVR0nGVHEUkUqrCNLl7yYnjfgSbN8s1dmCGwx5k/qrRJJ8CHdHzi9meLXqkh11FcJ98x3Kk2KBO8EHgoeE26hMwG3/Gxqqjh+M5yIqBvXo/drXPDtVj+aiEun3Zen5s7e2wf22irUD9MZQoglqIzf1rwjMhaT4fBPFRv9pzVIbSV9s4rgrFO6KBVvFUgiifzd1ER2Zm12OK/1CPmuG+OSQFNBESFnScU4LqrtbyYkZMtAlAK1SZjNaXeZ9joLnpzJvf5mVpdp7Y9C2DovjxCpen+VsOQshQRCfsPXJrCvAwjKGgLUeCrUGByPbGV2VWChh9zA2y3gKfRE5wFItsvi5tS+jwdkgHXiCv96sG/6QFK5fXnVZWmY+8OiSTr32NXykUVvYczlcpnzJjfSPzx1DHh8EuhCetJYDIyouza2tVM5Qp0OYYgeiJ8K2VKwaz75rfaSaMu7v62ckDoMq2DUv0EXZDnaaqfHAXqNZ4RYM1MNx4qAbp1SpdwUZfgMx6lHKpmvjfToVX5bH8TPD5yWwmMZOpqcNYR2kGm3pfltCNW1wfW1ZasnprIqQ6vxjTxF5kI/ufp8ZKzU="
  secret_access_key:
    secure: "CP3m4XVffUCZr+CHttQ+zamLzeyCgMlzvWeJdp5rZCOlW6xo9ykE0lSMAYJVdr3hKhclklPVmuGyC1W2C4t8jHOdiGBtNyysBA2tyEIBbDFKQUTPaoDrj4cqVJQ7hjI8hLHevKRzhgO5uvYX3qKYdhTDbDTe+SNcVbV+Q28OJprWpjMbZ5jjKOdxVMLvUZ3rPuiQ3IaVbG/qpadF/QnyAoovlxP2cL9OJKIHzQcyTEj+x9C2ykI4+H8PUaOpEIBYUAQjgZATXmhhecr3gm8GPff9tlZSSOeTBr2UryrA3MxJOE9kFk0du4/3T9U/LQXvk3T1uynoFkv7gvZsv8n76sBit5BRKnTvBWnM84HiyhVBBfo7SAh3kUGZYq+C7HxXQCKAmOnpRM0waRF/Lw4zZbZcGBmGOr+K24qOeda+xe+LeFl8JJ5p3Tvlk0Tz7tuJ3eC87lMqpVjZpiM1RaCRfbxP/kvQ3JzkTHGOiiKsGSeGXUqQBmKKhw3BpbfJ2pgfvGS4j6Ax1E03zTZE2J350kcxnUBT2AygUdtBz2poDP1TBRdmZA1vvEhaVmue3BW1022U1uZMoFduu6F5KU56pkAKueibcC7PknSsQME9kvqL7ig24kTnnAZn4ev2o5fwGTfGmv9Frcc+X8a9Wmc4/q0oTx7quOJnmxGAYN5bmso="